apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gvstio7gn-go 
  janus-idp.io/tekton: gvstio7gn-go
  backstage.io/kubernetes-id: gvstio7gn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gvstio7gn-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  