apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gvstio7gn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gvstio7gn-go 
  name: gvstio7gn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gvstio7gn-go 
